### ISSUE TITLE
Automatically start a new pomodoro

### ISSUE THREAD

**Issue by duncan-bayne** [konr/tomatinho#9]
I find myself occasionally running over the 25 minute mark when working.  When I finally come to stop the timer, it shows 25 minutes of solid work and _n_ minutes of break.  The break time counts against my percentage of time in full pomodoros.

What I'd like would be a setting which, if true, caused it to simply roll onto a new pomodoro automatically.

**Comment by amasad** [comment]
@duncan-bayne Did you find something else you use?

**Comment by duncan-bayne** [comment]
@amasad No, and sadly doing so (or extending tomatinho) is a way down my TODOs.

**Comment by TatriX** [comment]
I tried to fix Tomatihno to fit my needs but in the end I rewrote it from scratch.
https://github.com/TatriX/pomidor/
Feature requests are welcome.

**Comment by amasad** [comment]
@TatriX sweet! I'll try it out

**Comment by duncan-bayne** [comment]
Closing due to age.
